server:
  port: 30001
spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:file:./data/shop-ha.db
    username: admin
    password: admin
    driver-class-name: org.h2.Driver
