spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/shop
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    generate-ddl: true
    open-in-view: false
  messages:
    basename: exceptions